-- =====================================================================
-- Migration 13: seed recovered LMCP drug_sku rows  (consolidated)
-- Clean rows: 314 ; resolved-from-review: 11 ; TOTAL: 325
-- across 82 distinct drugs.
-- efda_approved defaults false ; global_registry_status defaults 'pending'.
-- Conflict key: uq_drug_sku_drug_form_strength (drug_id,dosage_form,strength) NULLS NOT DISTINCT
-- =====================================================================

-- SECTION A  (READ-ONLY)  Preflight: inn_names that do NOT resolve. Expect ZERO.
-- WATCH especially these edited names (newly typed, may not match drug.inn_name):
--   * Sunscreen
--   * Iodine + Potassium Iodide (... Lugol's Solution)
--   * Supportive hepatic preparation that contains essential phospholipids and vitamins
--   * Budesonide + Formoterol Fumarate
SELECT v.inn_name
FROM (VALUES
  ('Acetylcysteine'),
  ('Aciclovir'),
  ('Acyclovir/acyclovir'),
  ('Albumin'),
  ('Alendronate (Alendronic acid)'),
  ('Ampicillin'),
  ('Ampicillin + sulbactam'),
  ('Anti-D immunoglobulin'),
  ('Arsenic trioxide'),
  ('Atropine sulfate'),
  ('Azacitidine'),
  ('Bendamustine'),
  ('Benzathine benzylpenicillin'),
  ('Benzyl penicillin'),
  ('Betamethasone valerate+ Phenylephrine HCl + Lidocaine HCl'),
  ('Bisoprolol'),
  ('Budesonide + Formoterol Fumarate'),
  ('Cabergoline'),
  ('Carbetocin'),
  ('Carboplatin'),
  ('Cefalexin/cephalexin'),
  ('Cefazolin'),
  ('Chlorhexidine'),
  ('Chlorpheniramine malate'),
  ('Ciclosporin/ cyclosporine'),
  ('Clomifene citrate'),
  ('Clomipramine'),
  ('Cloxacillin'),
  ('Coagulation factor IX complex'),
  ('Codeine'),
  ('Cytarabine'),
  ('Deferoxamine mesylate (Deferoxamine)'),
  ('Dextrose'),
  ('Diethylcarbamazine citrate'),
  ('Digoxin immune fab (ovine)/ digoxin-specific, antibody fragments'),
  ('Ergometrine'),
  ('Ethyl alcohol'),
  ('Etoposide'),
  ('Ferrous sulphate + Folic acid'),
  ('Fludarabine'),
  ('Fludrocortisone'),
  ('Fluoxetine hydrochloride'),
  ('Gemcitabine'),
  ('Goserelin'),
  ('Hydralazine hydrochloride'),
  ('Hydroxycobalamin (Vitamin B12)'),
  ('Iodine + Potassium Iodide (Aqueous Iodine Oral Solution or Lugol''s Solution)'),
  ('Irinotecan'),
  ('Isoprenaline/Isoproterenol hydrochloride'),
  ('Isotretinoin'),
  ('Leovonorgestrel (D-Nongestrel)'),
  ('Levothyroxine'),
  ('Mesna'),
  ('Methadone'),
  ('Morphine'),
  ('Norepinephrine/noradrenaline'),
  ('Pancuronium bromide'),
  ('Penicillamine'),
  ('Pentamidine'),
  ('Pethidine hydrochloride (Meperidine)'),
  ('Phenobarbital'),
  ('Phenytoin'),
  ('Physostigmine'),
  ('Procaine- benzylpenicillin'),
  ('Proparacaine'),
  ('Propranolol hydrochloride'),
  ('Protamine sulfate'),
  ('Rocuronium'),
  ('Sevelamer'),
  ('Sulfur'),
  ('Sunscreen'),
  ('Supportive hepatic preparation that contains essential phospholipids and vitamins'),
  ('Tamoxifen'),
  ('Tretinoin (All-trans retinoic acid)'),
  ('Trihexyphenidyl (benzhexol)'),
  ('Valproic acid (sodium valproate)'),
  ('Verapamil hydrochloride'),
  ('Vincristine'),
  ('Vinorelbine'),
  ('Warfarin'),
  ('Zinc oxide'),
  ('Zoledronic acid')
) AS v(inn_name)
LEFT JOIN drug d ON d.inn_name = v.inn_name
WHERE d.id IS NULL
ORDER BY 1;

-- SECTION B  10-row sample, PREVIEW ONLY (rolls back).
BEGIN;
INSERT INTO drug_sku (drug_id, dosage_form, strength, base_unit)
SELECT d.id, v.dosage_form::dosage_form, v.strength, v.base_unit
FROM (VALUES
  ('Acetylcysteine', 'Tablet', '200mg', 'each'),
  ('Acetylcysteine', 'Tablet', '500mg', 'each'),
  ('Acetylcysteine', 'Tablet', '600mg', 'each'),
  ('Acetylcysteine', 'Tablet', '1000mg', 'each'),
  ('Acetylcysteine', 'Solution', '10%', 'bottle'),
  ('Acetylcysteine', 'Solution', '20%', 'bottle'),
  ('Acetylcysteine', 'Solution', '100mg/ml', 'bottle'),
  ('Acetylcysteine', 'Injection', '200mg/ml', 'vial'),
  ('Deferoxamine mesylate (Deferoxamine)', 'Injection', '500mg', 'vial'),
  ('Deferoxamine mesylate (Deferoxamine)', 'Injection', '2000mg', 'vial')
) AS v(inn_name, dosage_form, strength, base_unit)
JOIN drug d ON d.inn_name = v.inn_name
ON CONFLICT ON CONSTRAINT uq_drug_sku_drug_form_strength DO NOTHING
RETURNING (SELECT inn_name FROM drug WHERE id = drug_id), dosage_form, strength, base_unit;
ROLLBACK;

-- SECTION C  FULL seed (325 rows), PREVIEW (BEGIN ... ROLLBACK).
-- Check rows_inserted, then change ROLLBACK -> COMMIT to apply.
BEGIN;
WITH ins AS (
  INSERT INTO drug_sku (drug_id, dosage_form, strength, base_unit)
  SELECT d.id, v.dosage_form::dosage_form, v.strength, v.base_unit
  FROM (VALUES
    ('Acetylcysteine', 'Tablet', '200mg', 'each'),
    ('Acetylcysteine', 'Tablet', '500mg', 'each'),
    ('Acetylcysteine', 'Tablet', '600mg', 'each'),
    ('Acetylcysteine', 'Tablet', '1000mg', 'each'),
    ('Acetylcysteine', 'Solution', '10%', 'bottle'),
    ('Acetylcysteine', 'Solution', '20%', 'bottle'),
    ('Acetylcysteine', 'Solution', '100mg/ml', 'bottle'),
    ('Acetylcysteine', 'Injection', '200mg/ml', 'vial'),
    ('Deferoxamine mesylate (Deferoxamine)', 'Injection', '500mg', 'vial'),
    ('Deferoxamine mesylate (Deferoxamine)', 'Injection', '2000mg', 'vial'),
    ('Digoxin immune fab (ovine)/ digoxin-specific, antibody fragments', 'Injection', '40mg', 'vial'),
    ('Penicillamine', 'Tablet', '250mg', 'each'),
    ('Penicillamine', 'Capsule', '250mg', 'each'),
    ('Physostigmine', 'Injection', '1mg/ml', 'vial'),
    ('Sevelamer', 'Tablet', '400mg', 'each'),
    ('Sevelamer', 'Tablet', '800mg', 'each'),
    ('Aciclovir', 'Tablet', '200mg', 'each'),
    ('Aciclovir', 'Tablet', '400mg', 'each'),
    ('Aciclovir', 'Suspension', '200mg/ml', 'bottle'),
    ('Aciclovir', 'Injection', '200mg', 'vial'),
    ('Aciclovir', 'Injection', '250mg', 'vial'),
    ('Aciclovir', 'Injection', '500mg', 'vial'),
    ('Aciclovir', 'Injection', '1gm', 'vial'),
    ('Acyclovir/acyclovir', 'Tablet', '200mg', 'each'),
    ('Acyclovir/acyclovir', 'Tablet', '400mg', 'each'),
    ('Acyclovir/acyclovir', 'Suspension', '200mg/ml', 'bottle'),
    ('Acyclovir/acyclovir', 'Injection', '200mg', 'vial'),
    ('Acyclovir/acyclovir', 'Injection', '250mg', 'vial'),
    ('Acyclovir/acyclovir', 'Injection', '500mg', 'vial'),
    ('Acyclovir/acyclovir', 'Injection', '1gm', 'vial'),
    ('Ampicillin', 'Drops', '100mg/ml', 'bottle'),
    ('Ampicillin', 'Capsule', '250mg', 'each'),
    ('Ampicillin', 'Capsule', '500mg', 'each'),
    ('Ampicillin', 'Suspension', '125mg/5ml', 'bottle'),
    ('Ampicillin', 'Suspension', '250mg/5ml', 'bottle'),
    ('Ampicillin', 'Injection', '250mg', 'vial'),
    ('Ampicillin', 'Injection', '500mg', 'vial'),
    ('Ampicillin', 'Injection', '1000mg', 'vial'),
    ('Ampicillin + sulbactam', 'Injection', '500mg + 250mg', 'vial'),
    ('Ampicillin + sulbactam', 'Injection', '1gm+500mg', 'vial'),
    ('Ampicillin + sulbactam', 'Injection', '2gm +1gm', 'vial'),
    ('Benzathine benzylpenicillin', 'Injection', '0.6million IU', 'vial'),
    ('Benzathine benzylpenicillin', 'Injection', '1.2million IU', 'vial'),
    ('Benzathine benzylpenicillin', 'Injection', '2.4million IU', 'vial'),
    ('Benzyl penicillin', 'Injection', '1million IU', 'vial'),
    ('Benzyl penicillin', 'Injection', '5million IU', 'vial'),
    ('Benzyl penicillin', 'Injection', '10million', 'vial'),
    ('Benzyl penicillin', 'Injection', '20million IU', 'vial'),
    ('Cefalexin/cephalexin', 'Capsule', '250mg', 'each'),
    ('Cefalexin/cephalexin', 'Capsule', '500mg', 'each'),
    ('Cefalexin/cephalexin', 'Syrup', '125mg/5ml', 'bottle'),
    ('Cefalexin/cephalexin', 'Syrup', '250mg/5ml', 'bottle'),
    ('Cefazolin', 'Injection', '250mg', 'vial'),
    ('Cefazolin', 'Injection', '500mg', 'vial'),
    ('Cefazolin', 'Injection', '1gm', 'vial'),
    ('Cefazolin', 'Injection', '2gm', 'vial'),
    ('Cloxacillin', 'Capsule', '250mg', 'each'),
    ('Cloxacillin', 'Capsule', '500mg', 'each'),
    ('Cloxacillin', 'Injection', '250mg', 'vial'),
    ('Cloxacillin', 'Injection', '500mg', 'vial'),
    ('Cloxacillin', 'Syrup', '125mg/5m', 'bottle'),
    ('Cloxacillin', 'Syrup', '250mg/5ml', 'bottle'),
    ('Diethylcarbamazine citrate', 'Tablet', '50mg', 'each'),
    ('Diethylcarbamazine citrate', 'Tablet', '100mg', 'each'),
    ('Pentamidine', 'Solution', '300mg/vial', 'bottle'),
    ('Pentamidine', 'Injection', '200mg', 'vial'),
    ('Pentamidine', 'Injection', '300mg', 'vial'),
    ('Pentamidine', 'Injection', '200mg', 'vial'),
    ('Pentamidine', 'Injection', '300mg', 'vial'),
    ('Pentamidine', 'Solution', '300mg', 'bottle'),
    ('Pentamidine', 'Injection', '200mg', 'vial'),
    ('Procaine- benzylpenicillin', 'Injection', '4,000,000 IU', 'vial'),
    ('Chlorpheniramine malate', 'Syrup', '2mg/5ml', 'bottle'),
    ('Chlorpheniramine malate', 'Tablet', '2mg', 'each'),
    ('Chlorpheniramine malate', 'Tablet', '4mg', 'each'),
    ('Chlorpheniramine malate', 'Tablet', '5mg', 'each'),
    ('Chlorpheniramine malate', 'Tablet', '6mg', 'each'),
    ('Chlorpheniramine malate', 'Tablet', '10mg', 'each'),
    ('Chlorpheniramine malate', 'Injection', '10mg/ml', 'vial'),
    ('Arsenic trioxide', 'Injection', '1mg/1ml', 'vial'),
    ('Azacitidine', 'Injection', '100mg/vial', 'vial'),
    ('Azacitidine', 'Tablet', '200mg', 'each'),
    ('Azacitidine', 'Tablet', '300mg', 'each'),
    ('Bendamustine', 'Injection', '25mg', 'vial'),
    ('Bendamustine', 'Injection', '100mg', 'vial'),
    ('Bendamustine', 'Injection', '100mg/4mL (25mg/mL)', 'vial'),
    ('Cabergoline', 'Tablet', '0.5mg', 'each'),
    ('Carboplatin', 'Infusion', '10mg/ml', 'bag'),
    ('Cytarabine', 'Tablet', '50 mg', 'each'),
    ('Cytarabine', 'Injection', '50mg/5mL', 'vial'),
    ('Cytarabine', 'Injection', '10mg/mL', 'vial'),
    ('Cytarabine', 'Injection', '20mg/mL', 'vial'),
    ('Cytarabine', 'Injection', '100mg/mL', 'vial'),
    ('Cytarabine', 'Injection', '100mg', 'vial'),
    ('Cytarabine', 'Injection', '500mg', 'vial'),
    ('Cytarabine', 'Injection', '1000mg', 'vial'),
    ('Cytarabine', 'Injection', '2000mg', 'vial'),
    ('Etoposide', 'Capsule', '50mg', 'each'),
    ('Etoposide', 'Capsule', '100mg', 'each'),
    ('Etoposide', 'Injection', '20mg/ml', 'vial'),
    ('Etoposide', 'Injection', '100mg/5ml', 'vial'),
    ('Fludarabine', 'Injection', '50 mg (phosphate) in vial.', 'vial'),
    ('Fludarabine', 'Injection', '25mg/ml', 'vial'),
    ('Fludarabine', 'Tablet', '10mg', 'each'),
    ('Gemcitabine', 'Injection', '200mg', 'vial'),
    ('Gemcitabine', 'Injection', '1000mg', 'vial'),
    ('Gemcitabine', 'Injection', '38mg/mL', 'vial'),
    ('Gemcitabine', 'Injection', '100mg/ml', 'vial'),
    ('Goserelin', 'Implant', '3.6mg', 'each'),
    ('Goserelin', 'Implant', '10.8 mg', 'each'),
    ('Irinotecan', 'Injection', '20mg/ml', 'vial'),
    ('Irinotecan', 'Injection', '40mg/2ml', 'vial'),
    ('Irinotecan', 'Injection', '100mg/5ml', 'vial'),
    ('Mesna', 'Injection', '100 mg/ mL', 'vial'),
    ('Mesna', 'Injection', '400mg/ml', 'vial'),
    ('Mesna', 'Tablet', '400mg', 'each'),
    ('Tamoxifen', 'Tablet', '10mg', 'each'),
    ('Tamoxifen', 'Tablet', '20mg', 'each'),
    ('Tamoxifen', 'Solution', '10mg/5ml', 'bottle'),
    ('Vincristine', 'Injection', '1mg', 'vial'),
    ('Vincristine', 'Injection', '2mg', 'vial'),
    ('Vincristine', 'Injection', '5mg', 'vial'),
    ('Vincristine', 'Injection', '10mg', 'vial'),
    ('Vincristine', 'Injection', '1mg/ml', 'vial'),
    ('Vinorelbine', 'Injection', '10 mg/mL in vial.', 'vial'),
    ('Vinorelbine', 'Capsule', '30mg', 'each'),
    ('Vinorelbine', 'Solution', '0.2mg', 'bottle'),
    ('Zoledronic acid', 'Infusion', '4mg/5 ml', 'bag'),
    ('Zoledronic acid', 'Infusion', '5mg/100ml', 'bag'),
    ('Albumin', 'Injection', '5%', 'vial'),
    ('Albumin', 'Injection', '20% in100ml', 'vial'),
    ('Albumin', 'Injection', '25% in 50 ml', 'vial'),
    ('Albumin', 'Injection', '100 ml', 'vial'),
    ('Coagulation factor IX complex', 'Injection', '500IU', 'vial'),
    ('Coagulation factor IX complex', 'Injection', '1000IU', 'vial'),
    ('Ferrous sulphate + Folic acid', 'Capsule', '150mg + 0.5mg', 'each'),
    ('Ferrous sulphate + Folic acid', 'Capsule', '60mg +0.4mg', 'each'),
    ('Ferrous sulphate + Folic acid', 'Tablet', '150mg +0.5mg', 'each'),
    ('Protamine sulfate', 'Injection', '10mg/ml', 'vial'),
    ('Protamine sulfate', 'Injection', '25mg/ml', 'vial'),
    ('Warfarin', 'Tablet', '1mg', 'each'),
    ('Warfarin', 'Tablet', '2mg', 'each'),
    ('Warfarin', 'Tablet', '2.5mg', 'each'),
    ('Warfarin', 'Tablet', '3mg', 'each'),
    ('Warfarin', 'Tablet', '4mg', 'each'),
    ('Warfarin', 'Tablet', '5mg', 'each'),
    ('Warfarin', 'Tablet', '6mg', 'each'),
    ('Warfarin', 'Tablet', '7.5mg', 'each'),
    ('Warfarin', 'Tablet', '10mg', 'each'),
    ('Bisoprolol', 'Tablet', '1.25mg', 'each'),
    ('Bisoprolol', 'Tablet', '2.5mg', 'each'),
    ('Bisoprolol', 'Tablet', '5mg', 'each'),
    ('Bisoprolol', 'Tablet', '10mg', 'each'),
    ('Hydralazine hydrochloride', 'Tablet', '10mg', 'each'),
    ('Hydralazine hydrochloride', 'Tablet', '25mg', 'each'),
    ('Hydralazine hydrochloride', 'Tablet', '50mg', 'each'),
    ('Hydralazine hydrochloride', 'Tablet', '100mg', 'each'),
    ('Hydralazine hydrochloride', 'Injection', '20mg/ml', 'vial'),
    ('Hydralazine hydrochloride', 'Injection', '20mg/ml', 'vial'),
    ('Hydralazine hydrochloride', 'Injection', '5mg/ml', 'vial'),
    ('Hydralazine hydrochloride', 'Injection', '20mg/ml', 'vial'),
    ('Isoprenaline/Isoproterenol hydrochloride', 'Injection', '0.02mg', 'vial'),
    ('Isoprenaline/Isoproterenol hydrochloride', 'Injection', '0.2mg/ml', 'vial'),
    ('Norepinephrine/noradrenaline', 'Injection', '1mg/ml', 'vial'),
    ('Norepinephrine/noradrenaline', 'Injection', '8mg/ml', 'vial'),
    ('Phenytoin', 'Injection', '250mg', 'vial'),
    ('Verapamil hydrochloride', 'Injection', '2.5mg/ml', 'vial'),
    ('Verapamil hydrochloride', 'Tablet', '40mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '80mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '120mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '240mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '40mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '60mg', 'each'),
    ('Verapamil hydrochloride', 'Tablet', '80mg', 'each'),
    ('Verapamil hydrochloride', 'Injection', '25mg/ml', 'vial'),
    ('Ethyl alcohol', 'Solution', '70%', 'bottle'),
    ('Isotretinoin', 'Capsule', '10mg', 'each'),
    ('Isotretinoin', 'Capsule', '20mg', 'each'),
    ('Sulfur', 'Ointment', '5%', 'tube'),
    ('Sulfur', 'Ointment', '10%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Cream', '0.02%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Cream', '0.025%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Cream', '0.03%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Gel', '0.01%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Gel', '0.025%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Gel', '0.03%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Lotion', '0.025%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Lotion', '0.05%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Lotion', '0.03%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Lotion', '0.05%', 'tube'),
    ('Tretinoin (All-trans retinoic acid)', 'Ointment', '0.05%', 'tube'),
    ('Zinc oxide', 'Lotion', '15%', 'tube'),
    ('Clomifene citrate', 'Tablet', '50mg', 'each'),
    ('Clomifene citrate', 'Tablet', '25 mg', 'each'),
    ('Clomifene citrate', 'Tablet', '50mg', 'each'),
    ('Fludrocortisone', 'Tablet', '0.1mg', 'each'),
    ('Fludrocortisone', 'Tablet', '0.3 mg', 'each'),
    ('Leovonorgestrel (D-Nongestrel)', 'Implant', '75mg', 'each'),
    ('Leovonorgestrel (D-Nongestrel)', 'Implant', '108mg', 'each'),
    ('Leovonorgestrel (D-Nongestrel)', 'Tablet', '0.03mg (minipill)', 'each'),
    ('Leovonorgestrel (D-Nongestrel)', 'Tablet', '0.75mg', 'each'),
    ('Leovonorgestrel (D-Nongestrel)', 'Tablet', '1.5mg', 'each'),
    ('Levothyroxine', 'Tablet', '25mcg', 'each'),
    ('Levothyroxine', 'Tablet', '50mcg', 'each'),
    ('Levothyroxine', 'Tablet', '75mcg', 'each'),
    ('Levothyroxine', 'Tablet', '100mcg', 'each'),
    ('Levothyroxine', 'Tablet', '200mcg', 'each'),
    ('Chlorhexidine', 'Solution', '0.12%', 'bottle'),
    ('Dextrose', 'Injection', '2.5%', 'vial'),
    ('Dextrose', 'Injection', '5%', 'vial'),
    ('Dextrose', 'Injection', '10%', 'vial'),
    ('Dextrose', 'Injection', '40%', 'vial'),
    ('Dextrose', 'Injection', '50%', 'vial'),
    ('Atropine sulfate', 'Injection', '1mg/ml', 'vial'),
    ('Atropine sulfate', 'Ointment', '1%', 'tube'),
    ('Atropine sulfate', 'Drops', '0.5%', 'bottle'),
    ('Atropine sulfate', 'Drops', '1%', 'bottle'),
    ('Atropine sulfate', 'Injection', '600mcg/ml', 'vial'),
    ('Atropine sulfate', 'Injection', '1mg/ml', 'vial'),
    ('Betamethasone valerate+ Phenylephrine HCl + Lidocaine HCl', 'Ointment', '0.5mg+1mg+25mg', 'tube'),
    ('Propranolol hydrochloride', 'Tablet', '20mg', 'each'),
    ('Propranolol hydrochloride', 'Injection', '1mg/ml', 'vial'),
    ('Propranolol hydrochloride', 'Tablet', '10mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '40mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '10mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '20 mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '40mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '60mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '80 mg', 'each'),
    ('Propranolol hydrochloride', 'Capsule', '60mg', 'each'),
    ('Propranolol hydrochloride', 'Capsule', '80mg', 'each'),
    ('Propranolol hydrochloride', 'Capsule', '120mg', 'each'),
    ('Propranolol hydrochloride', 'Capsule', '160mg', 'each'),
    ('Propranolol hydrochloride', 'Injection', '1mg/ml', 'vial'),
    ('Propranolol hydrochloride', 'Tablet', '10mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '40mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '60mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '80mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '10mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '20mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '40mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '60mg', 'each'),
    ('Propranolol hydrochloride', 'Tablet', '80mg', 'each'),
    ('Propranolol hydrochloride', 'Injection', '1mg/ml', 'vial'),
    ('Anti-D immunoglobulin', 'Injection', '120mcg', 'vial'),
    ('Anti-D immunoglobulin', 'Injection', '150mcg/ml', 'vial'),
    ('Anti-D immunoglobulin', 'Injection', '300mcg', 'vial'),
    ('Alendronate (Alendronic acid)', 'Tablet', '70mg', 'each'),
    ('Pancuronium bromide', 'Injection', '2mg/ml', 'vial'),
    ('Rocuronium', 'Injection', '10mg/ml', 'vial'),
    ('Clomipramine', 'Capsule', '10mg', 'each'),
    ('Clomipramine', 'Capsule', '25mg', 'each'),
    ('Clomipramine', 'Capsule', '50mg', 'each'),
    ('Clomipramine', 'Tablet', '10mg', 'each'),
    ('Clomipramine', 'Tablet', '25mg', 'each'),
    ('Clomipramine', 'Tablet', '50mg', 'each'),
    ('Fluoxetine hydrochloride', 'Capsule', '20mg', 'each'),
    ('Methadone', 'Injection', '10mg/ml', 'vial'),
    ('Methadone', 'Injection', '20mg/ml', 'vial'),
    ('Methadone', 'Tablet', '5mg', 'each'),
    ('Methadone', 'Tablet', '5mg', 'each'),
    ('Methadone', 'Tablet', '10mg', 'each'),
    ('Methadone', 'Tablet', '40mg', 'each'),
    ('Morphine', 'Injection', '10mg/ml', 'vial'),
    ('Morphine', 'Injection', '20mg/ml', 'vial'),
    ('Morphine', 'Injection', '30mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '25mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '50mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '75mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '100mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Syrup', '50mg/5mL', 'bottle'),
    ('Pethidine hydrochloride (Meperidine)', 'Tablet', '50mg', 'each'),
    ('Pethidine hydrochloride (Meperidine)', 'Tablet', '100mg', 'each'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '25mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '50mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '75mg/ml', 'vial'),
    ('Pethidine hydrochloride (Meperidine)', 'Injection', '100mg/ml', 'vial'),
    ('Phenobarbital', 'Capsule', '50mg', 'each'),
    ('Phenobarbital', 'Capsule', '100mg', 'each'),
    ('Phenobarbital', 'Tablet', '15mg', 'each'),
    ('Phenobarbital', 'Tablet', '30mg', 'each'),
    ('Phenobarbital', 'Tablet', '60mg', 'each'),
    ('Phenobarbital', 'Tablet', '100mg', 'each'),
    ('Phenobarbital', 'Injection', '50mg/ml', 'vial'),
    ('Phenobarbital', 'Suppository', '30mg', 'each'),
    ('Phenobarbital', 'Suppository', '60mg', 'each'),
    ('Phenobarbital', 'Elixir', '20mg/5ml', 'bottle'),
    ('Trihexyphenidyl (benzhexol)', 'Tablet', '2mg', 'each'),
    ('Trihexyphenidyl (benzhexol)', 'Tablet', '5mg', 'each'),
    ('Valproic acid (sodium valproate)', 'Syrup', '200mg/5ml', 'bottle'),
    ('Valproic acid (sodium valproate)', 'Tablet', '200mg', 'each'),
    ('Valproic acid (sodium valproate)', 'Tablet', '500mg', 'each'),
    ('Carbetocin', 'Injection', '100mcg/ml', 'vial'),
    ('Ergometrine', 'Injection', '0.25 mg/ml', 'vial'),
    ('Ergometrine', 'Injection', '0.5 mg/ml', 'vial'),
    ('Ergometrine', 'Tablet', '0.25mg', 'each'),
    ('Ergometrine', 'Tablet', '0.5mg', 'each'),
    ('Ciclosporin/ cyclosporine', 'Drops', '0.05%', 'bottle'),
    ('Ciclosporin/ cyclosporine', 'Drops', '0.2%', 'bottle'),
    ('Ciclosporin/ cyclosporine', 'Drops', '1%', 'bottle'),
    ('Ciclosporin/ cyclosporine', 'Drops', '2%', 'bottle'),
    ('Proparacaine', 'Injection', '2%', 'vial'),
    ('Proparacaine', 'Drops', '0.5%', 'bottle'),
    ('Codeine', 'Tablet', '30mg', 'each'),
    ('Codeine', 'Tablet', '30mg', 'each'),
    ('Codeine', 'Injection', '30mg/ml', 'vial'),
    ('Hydroxycobalamin (Vitamin B12)', 'Injection', '100mcg/ml', 'vial'),
    ('Hydroxycobalamin (Vitamin B12)', 'Injection', '1000mcg/ml', 'vial'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '50mcg', 'each'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '100mcg', 'each'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '250mcg', 'each'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '500mcg', 'each'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '1000mcg', 'each'),
    ('Hydroxycobalamin (Vitamin B12)', 'Tablet', '2500mcg', 'each'),
    ('Sunscreen', 'Lotion', 'With SPF 30+ (UVA+UVB block)', 'tube'),
    ('Iodine + Potassium Iodide (Aqueous Iodine Oral Solution or Lugol''s Solution)', 'Solution', '5% + 10%', 'bottle'),
    ('Supportive hepatic preparation that contains essential phospholipids and vitamins', 'Capsule', NULL, 'each'),
    ('Methadone', 'Liquid', '5mg/ml', 'bottle'),
    ('Methadone', 'Liquid', '10mg/ml', 'bottle'),
    ('Morphine', 'Other', '3mg', 'each'),
    ('Morphine', 'Liquid', '30mg/ml', 'bottle'),
    ('Budesonide + Formoterol Fumarate', 'Spray', '(80mcg +4.5mcg)/dose', 'each'),
    ('Budesonide + Formoterol Fumarate', 'Spray', '(60mcg +4.5mcg)/dose', 'each'),
    ('Codeine', 'Liquid', '10mg/5ml', 'bottle'),
    ('Codeine', 'Liquid', '15mg/5ml', 'bottle')
  ) AS v(inn_name, dosage_form, strength, base_unit)
  JOIN drug d ON d.inn_name = v.inn_name
  ON CONFLICT ON CONSTRAINT uq_drug_sku_drug_form_strength DO NOTHING
  RETURNING 1
)
SELECT count(*) AS rows_inserted FROM ins;
COMMIT;

